# Generated by Django 3.0.8 on 2020-07-03 17:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200703_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 3, 17, 38, 4, 770223, tzinfo=utc)),
        ),
    ]
