# Generated by Django 3.0.8 on 2020-07-04 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200703_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 16, 44, 11, 408464, tzinfo=utc)),
        ),
    ]
