# Generated by Django 3.0.2 on 2020-07-26 13:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200704_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 26, 13, 51, 17, 672175, tzinfo=utc)),
        ),
    ]
